language:
  - python

python:
  - "3.6"

before_install:
  - sudo apt-get install unar

install:
  - pip install kaggle
  - pip install -r requirements.txt

script:
  - kaggle competitions download -c trackml-particle-identification -f train_sample.zip -p data/
  - unar data/train_sample.zip -o data/
  - pytest -s
